# Copyright Paion Data
---
name: CI/CD

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master

jobs:
  guide-build:
    name: The Guide Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.0"
      - run: |
          gem install jekyll
          bundle install
          bundle exec jekyll build
